apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: t1-sample-app
  name: t1-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t1-sample-app
  template:
    metadata:
      labels:
        app: t1-sample-app
    spec:
      containers:
      - name: t1-sample-app
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false



