apiVersion: v1
kind: Service
metadata:
  labels:
    app: t1-sample-app
  name: t1-sample-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: t1-sample-app
  type: LoadBalancer
