apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t1-sample-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: tenant-1
  source:
    path: manifest/tennant-1/sample-app/overlays/dev
    repoURL: https://github.com/multi-tenant-example-org/tenant-1.git
    targetRevision: HEAD
